./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 1 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
./lemipc /home/ 2 &
